# This is the minimal config file for an NNI experiment.
# Use "nnictl create --config config.yml" to launch this experiment.
# Afterwards, you can check "config_detailed.yml" for more explanation.

searchSpaceFile: search_space.json
trialCommand: python3 finetune_sa_bert.py  # NOTE: change "python3" to "python" if you are using Windows
trialGpuNumber: 1
trialConcurrency: 8
maxTrialNumber: 8
tuner:
  # name: TPE
  # classArgs:
  #   optimize_mode: maximize
  name: GridSearch
trainingService:
  platform: local
  useActiveGpu: False
  
